#!/bin/bash
set -e
set -o pipefail

cleanup() {
  echo "Cleanup backup older than $CLEANUP_OLDER_THAN days"
  toberemove=$(find /backups/ -type f -not -name ".*" -mtime +$CLEANUP_OLDER_THAN | wc -l)
  echo "Will try to remove $toberemove files"
  find /backups/ -type f -not -name ".*" -mtime +$CLEANUP_OLDER_THAN -exec rm {} \;
}

if [ -z "$DATABASE_HOST" ]; then echo "Error: DATABASE_HOST not set"; echo "Finished: FAILURE"; exit 1; fi
if [ -z "$DATABASE_USER" ]; then echo "Error: DATABASE_USER not set"; echo "Finished: FAILURE"; exit 1; fi
if [ -z "$DATABASE_NAME" ]; then echo "Error: DATABASE_NAME not set"; echo "Finished: FAILURE"; exit 1; fi
if [ -z "$DATABASE_PASSWORD" ]; then echo "Error: DATABASE_PASSWORD not set"; echo "Finished: FAILURE"; exit 1; fi

if [ -n "$CLEANUP_OLDER_THAN" ]; then cleanup;  fi

echo 'creating backup archive of /var/www/html'
tar --create --gzip -vv --directory="/var/www/html/" --file="/tmp/backup_`date '+%Y%m%d'`.tar.gz" "./"

echo 'creating database dump'
if [ "$DATABASE_CLIENT" == "mariadb" ]; then
  mariadb-dump --host="${DATABASE_HOST}" --add-drop-table --no-tablespaces --user="${DATABASE_USER}" --password="${DATABASE_PASSWORD}" "${DATABASE_NAME}" --single-transaction | bzip2 -c > "/tmp/backup_`date '+%Y%m%d'`.sql.bz2"
else
  mysqldump --host="${DATABASE_HOST}" --add-drop-table --no-tablespaces --user="${DATABASE_USER}" --password="${DATABASE_PASSWORD}" "${DATABASE_NAME}" --single-transaction --column-statistics=0 | bzip2 -c > "/backups/backup_`date '+%Y%m%d'`.sql.bz2"
fi

echo 'moving backup files to /backups'
mv /tmp/backup_`date '+%Y%m%d'`.tar.gz /backups/
mv /tmp/backup_`date '+%Y%m%d'`.sql.bz2 /backups/

echo 'Finished: SUCCESS'
